### PR TITLE
Added PAL support

### LINKED ISSUE #14: I live in a PAL country. Could this work with PAL?

### PR DESCRIPTION
**Pull request by schlarmann**
Made some changes to the video timings to allow for PAL broadcasts. I didn't change the actual code for colour generation since I only wanted to use it with a B/W television.

Semi-Fixes #14

### CODE REVIEW

**Comment by cnlohr** [comment]
@schlarmann , This is extremely cool, but this looks like if merged would break NTSC, since some of the buffers aren't guarded behind `-DPAL` flags.  Especially surrounding the tablemaker, etc.  Can you add the extra guarding to make it be able to produce either PAL or NTSC?

**Comment by schlarmann** [comment]
Sorry for the radio silence the last months, I was busy with university stuff.
Now the tablemaker.c generates both tables (for NTSC and PAL) so switching between them can be done completely with `-DPAL`. With my multisync (PAL / SECAM) TV I can now receive both broadcasts (in black and white), so I think I didn't break NTSC with this change, but this should probably be checked with an actual NTSC TV before merging.

**Comment by cnlohr** [comment]
Can you try squashing all of your commits?  I really can't figure out what exactly is going on here, but it looks like you changed much more than you intended, @schlarmann.

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits

**Comment by schlarmann** [comment]
Like this?
Sorry for the confusion, I just noticed after pushing that I forgot to update the README with new documentation and to set up the user.cfg to build NTSC by default so I made the 2 other commits to correct for this.

**Comment by cnlohr** [comment]
YESS LIKE THAT! I will review soon.

**Comment by cnlohr** [comment]
YES! This is beautiful 🧑‍🍳😙🤌

**Pull request merged**
